# Generated by Django 2.2.7 on 2019-11-07 21:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('Temperature Sensor', 'Temperature Sensor'), ('Voltage Meter', 'Voltage Meter'), ('Current Meter', 'Current Meter'), ('Power Meter', 'Power Meter')], default='Temperature Sensor', max_length=128)),
                ('unit', models.PositiveIntegerField(choices=[(1, 'V'), (2, '°C'), (3, 'A'), (4, 'W')], default=1)),
            ],
            options={
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('record_time', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'records',
            },
        ),
        migrations.CreateModel(
            name='DeviceRecords',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=3, default=0, max_digits=11)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='echo.Devices')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='echo.Records')),
            ],
            options={
                'db_table': 'device_records',
            },
        ),
    ]
